"""updated_db_fields

Revision ID: 19ab040231b5
Revises: 208d86c93486
Create Date: 2025-05-07 19:32:20.465156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ab040231b5'
down_revision = '208d86c93486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'media', ['media_id'], ['media_id'])

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_uploaded_date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_column('media_uploaded_date')

    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('media_id')

    # ### end Alembic commands ###
