"""updated_db_fields

Revision ID: 208d86c93486
Revises: f3dd608ecb61
Create Date: 2025-05-07 19:18:33.677158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208d86c93486'
down_revision = 'f3dd608ecb61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_journal_entry_media_id'), ['media_id'], unique=False)
        batch_op.create_foreign_key(None, 'media', ['media_id'], ['media_id'])

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_uploaded_date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_column('media_uploaded_date')

    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_journal_entry_media_id'))
        batch_op.drop_column('media_id')

    # ### end Alembic commands ###
