"""entries_update

Revision ID: 2ec8dcaf3908
Revises: 9691a1b4c89c
Create Date: 2025-05-04 16:11:36.525110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec8dcaf3908'
down_revision = '9691a1b4c89c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.VARCHAR(length=256), nullable=True))

    # ### end Alembic commands ###
