"""added_fields

Revision ID: f3dd608ecb61
Revises: 2ec8dcaf3908
Create Date: 2025-05-07 14:28:17.882638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3dd608ecb61'
down_revision = '2ec8dcaf3908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entry_media',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entry.entry_id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['tag.tag_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('entry_id', 'media_id')
    )
    with op.batch_alter_table('journal_entry_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entry_media_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('journal_entry_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entry_media_user_id'))

    op.drop_table('journal_entry_media')
    # ### end Alembic commands ###
