"""users table

Revision ID: 244f965d9ad5
Revises: 6157e02b3bf6
Create Date: 2025-05-01 16:45:46.835504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244f965d9ad5'
down_revision = '6157e02b3bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('journal_entry_tag',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entry.entry_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ),
    sa.PrimaryKeyConstraint('entry_id', 'tag_id')
    )
    op.create_table('media',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('media_format', sa.String(length=10), nullable=False),
    sa.Column('media_file_path', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entry.entry_id'], ),
    sa.PrimaryKeyConstraint('media_id')
    )
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('journal_title', sa.String(length=1024), nullable=False))
        batch_op.add_column(sa.Column('journal_entry', sa.String(length=64000), nullable=False))
        batch_op.add_column(sa.Column('entry_published', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('last_mod_date', sa.DateTime(), nullable=False))
        batch_op.drop_index('ix_journal_entry_timestamp')
        batch_op.create_index(batch_op.f('ix_journal_entry_entry_published'), ['entry_published'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'])
        batch_op.drop_column('id')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('body')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('about_me',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('about_me',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=140), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_journal_entry_entry_published'))
        batch_op.create_index('ix_journal_entry_timestamp', ['timestamp'], unique=False)
        batch_op.drop_column('last_mod_date')
        batch_op.drop_column('entry_published')
        batch_op.drop_column('journal_entry')
        batch_op.drop_column('journal_title')
        batch_op.drop_column('entry_id')

    op.drop_table('media')
    op.drop_table('journal_entry_tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
